name = "Chill Maadi"
author = "FlamesMarshal"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd79841677a042727d5def0cecc2d793f58b7e76650c65b90da3d4225114ad1e"

[versions]
fabric = "0.19.5"
minecraft = "1.21.8"
