name = "Chill Maadi"
author = "FlamesMarshal"
version = "0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efa76d929a654226cbc535cc0ab0b136f8e99bdffffe8ed5c690279c53e66b85"

[versions]
fabric = "0.19.5"
minecraft = "1.21.8"
